---
kind: ConfigMap
apiVersion: v1
metadata:
  name: kube-synchronizer
  namespace: kube-system
data:
  ConfigMap: ConfigMap
  Namespace: Namespace
  Node: Node
  PersistentVolumeClaim: PersistentVolumeClaim
  PersistentVolume: PersistentVolume
  Pod: Pod
  ReplicationController: ReplicationController
  Secret: Secret
  ServiceAccount: ServiceAccount
  CustomResourceDefinition: CustomResourceDefinition
  DaemonSet: DaemonSet
  Deployment: Deployment
  ReplicaSet: ReplicaSet
  StatefulSet: StatefulSet
  CronJob: CronJob
  Job: Job
  NetworkPolicy: NetworkPolicy
  Ingress: Ingress
  ClusterRoleBinding: ClusterRoleBinding
  ClusterRole: ClusterRole
  RoleBinding: RoleBinding
  Role: Role
  StorageClass: StorageClass
  Service: Service
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata: 
  name: "kube-synchronizer"
  namespace: "kube-system"
  labels: 
    name: "kube-synchronizer"
spec: 
  replicas: 1
  selector: 
    matchLabels:
      name: "kube-synchronizer"
  template: 
    metadata: 
      labels: 
        name: "kube-synchronizer"
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
      - name: "kube-synchronizer"
        image: "registry.cn-beijing.aliyuncs.com/kubesys/kubernetes-synchronizer:v1.0.0-amd64"
        imagePullPolicy: "IfNotPresent"
        command: 
        - "java"
        - "-jar"
        - "kubernetes-synchronizer.jar"
        env:
        - name: URL
          value: https://172.17.104.190:6443
        - name: TOKEN
          value: eyJhbGciOiJSUzI1NiIsImtpZCI6IjBUUGxHRE5YdG5FRkswS3NVNHhEbHctTDFwbXZOY09LQ3ZydHBUWTVfR00ifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJrdWJlcm5ldGVzLWNsaWVudC10b2tlbi1nNWIyYyIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJrdWJlcm5ldGVzLWNsaWVudCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImU5YmRlNmJhLTE0ODAtNGViMC1hMWYxLTFkMjE1YWFjNTk4ZCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprdWJlLXN5c3RlbTprdWJlcm5ldGVzLWNsaWVudCJ9.KjssR2onK6yqk4dxf6r8yFemS9HYqxrguTzMqgkwnSBZMf9x4VrH0WBmaPokcEKBigCsH12Ey501eEWvy0jBbQrwZQzc-f6AdXwI9EOX7anH0jhB7EZketEJlBlSGOgc6FVFIveOkRGMvMdjuE7ZusVj_3RsddiOqErDCaE7-n1NwWnkVb-T18w-8zLSI9QQZ5YI4VnAnuqINYOao4dds8jfV3wnl0hFzxzLDq6V8839PurSHwOa7yiVWTc3WUzu4TtRcZhLQ6irOB3BnYP4oDdD4ISeWXrinabux-zj4LNM3nxuKVB-zIRGNP_mWJCr4S4xzIimhiDXWsXLuyVxdg
        volumeMounts: 
        - name: "kubetoken"
          mountPath: "/etc/kubernetes"
      volumes: 
      - name: "kubetoken"
        hostPath:
          path: "/etc/kubernetes"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: kube-database
  namespace: kube-system
data:
  DRIVER: com.mysql.cj.jdbc.Driver
  JDBC: jdbc:mysql://kube-database.kube-system:3306
  DATABASE: kube
  USER: root
  PASSWORD: onceas
--- 
apiVersion: "apps/v1"
kind: "Deployment"
metadata: 
  name: "kube-database"
  namespace: "kube-system"
  labels: 
    name: "kube-database"
spec: 
  replicas: 1
  selector: 
    matchLabels:
      name: "kube-database"
  template: 
    metadata: 
      labels: 
        name: "kube-database"
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
      - name: "mariadb"
        image: "mariadb:10.5.3"
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 3306
        env:
        - name: "MYSQL_ROOT_PASSWORD"
          value: "onceas"
        volumeMounts:
        - name: "mysqldata"
          mountPath: "/var/lib/mysql"
      - name: "adminer"
        image: "adminer:4.7.7-standalone"
        imagePullPolicy: "IfNotPresent"
        ports: 
        - containerPort: 8080
      volumes: 
      - name: "mysqldata"
        hostPath:
          path: "/var/lib/mysql"
---
apiVersion: v1
kind: Service
metadata:
  name: kube-database
  namespace: kube-system
  labels: 
    name: kube-database
spec:
  type: NodePort
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
    name: mysql-port
    nodePort: 30306
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: adminer-port
    nodePort: 30307
  selector:
    name: kube-database
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: kube-rabbitmq
  namespace: kube-system
data:
  HOST: kube-rabbitmq.kube-system
  USER: root
  PASSWORD: onceas
  PORT: "5672"
  QUEUE: kube-events
--- 
apiVersion: "apps/v1"
kind: "Deployment"
metadata: 
  name: "kube-rabbitmq"
  namespace: "kube-system"
  labels: 
    name: "kube-rabbitmq"
spec: 
  replicas: 1
  selector: 
    matchLabels:
      name: "kube-rabbitmq"
  template: 
    metadata: 
      labels: 
        name: "kube-rabbitmq"
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
      - name: "rabbitmq"
        image: "bitnami/rabbitmq:3.8.5"
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 15672  
        - containerPort: 5672  
        env:
        - name: "RABBITMQ_USERNAME"
          value: "root"
        - name: "RABBITMQ_PASSWORD"
          value: "onceas" 
        volumeMounts:
        - name: "rabbit-persistent-storage"
          mountPath: "/bitnami"
      volumes: 
      - name: "rabbit-persistent-storage"
        hostPath:
          path: "/var/lib/rabbitmq"
---
apiVersion: v1
kind: Service
metadata:
  name: kube-rabbitmq
  namespace: kube-system
  labels: 
    name: kube-rabbitmq
spec:
  type: NodePort
  ports:
  - name: rabbitmq-management-port
    nodePort: 30305  
    port: 15672  
    protocol: TCP  
    targetPort: 15672  
  - name: rabbitmq-port 
    nodePort: 30304   
    port: 5672   
    protocol: TCP   
    targetPort: 5672
  selector:
    name: kube-rabbitmq
