FROM openjdk:11.0.7-slim

RUN mkdir -p /home/kubeext-plugin

ADD kubeext-plugin.jar /home/kubeext-plugin

WORKDIR /home/kubeext-plugin

#RUN java -jar kubevirt-controller-1.3.0-jar-with-dependencies.jar
