FROM registry.cn-beijing.aliyuncs.com/kubesys/kubernetes-java-base:jdk8-amd64

ADD kubernetes-synchronizer.jar /home/kubernetes-synchronizer.jar

WORKDIR /home

#RUN java -jar kubernetes-synchronizer.jar
